name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main   # change to master if your repo uses master

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sumit111-u
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "output"
